download changed on Tue 20 Mar 2012 10:19:01 EST

diff --git a/download b/download
--- a/download
+++ b/download
@@ -29,7 +29,46 @@ source includes/functions
 
 read -p "What is the actual domain of the website: " domain
 
+############################################################################# 
+# Check settings
+#############################################################################
 
+
+#Check vhost exist
+if [ -f $APACHEDIR/other/$1.$SERVER.conf ]; then
+  echo vhost $1.$SERVER is already existed
+  exit
+fi
+
+#Check project directory exist
+if [ -d $WWW/$1 ]; then
+  echo Folder $1 is already existed
+  exit
+fi
+
+#Check drush settings
+if [ ! -d /Users/$USER/.drush ]; then
+	echo ".drush folder not found"
+	exit
+fi
+
+#Check db exist
+
+read -s -p "Enter mysql root password: " rootpass
+
+#Test mysql connection
+while ! mysql -u root -p$rootpass  -e ";" ; do
+       read -s -p "Can't connect, please retry: " rootpass
+done
+echo "";
+
+check_db_exist $1_db $rootpass
+db_exist=$?
+
+if [ $db_exist = 1 ]; then	
+	echo database $1_db alread exist
+	exit
+fi
 
 #Check remote status
 status=$(drush @$1.$2 status|grep "Drupal bootstrap"|awk '{ print $4 }')
