startup changed on Tue 20 Mar 2012 10:38:39 EST

diff --git a/startup b/startup
--- a/startup
+++ b/startup
@@ -10,6 +10,27 @@ source includes/functions
 
 
 ############################################################################# 
+# Get Opts
+#############################################################################
+
+while getopts ":a" opt; do
+  case $opt in
+    a)
+      echo "-a was triggered!" >&2
+		shift $((OPTIND-1))
+      ;;
+    m)
+      echo "-a was triggered!" >&2
+		shift $((OPTIND-1))
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+		shift $((OPTIND-1))
+      ;;
+  esac
+done
+
+############################################################################# 
 # Check usage
 #############################################################################
 
