startup changed on Tue 20 Mar 2012 10:40:48 EST

diff --git a/startup b/startup
--- a/startup
+++ b/startup
@@ -16,18 +16,18 @@ source includes/functions
 while getopts ":a" opt; do
   case $opt in
     a)
-      echo "-a was triggered!" >&2
+		echo "-a was triggered!" >&2
 		shift $((OPTIND-1))
-      ;;
+		;;
     m)
-      echo "-a was triggered!" >&2
-		
+		echo "Manual install mode" >&2
+		MANUAL_INSTALL=1
 		shift $((OPTIND-1))
-      ;;
+		;;
     \?)
-      echo "Invalid option: -$OPTARG" >&2
+		echo "Invalid option: -$OPTARG" >&2
 		exit 1
-      ;;
+		;;
   esac
 done
 
