spearte subtheme creation into a new function called subtheme

diff --git a/upload b/upload
--- a/upload
+++ b/upload
@@ -9,6 +9,32 @@ source includes/config
 source includes/functions
 
 ############################################################################# 
+# Get Opts
+#############################################################################
+usage()
+{
+cat << EOF
+usage: $0 SITE [live | dev]
+
+EOF
+}
+while getopts ":h" opt; do
+  case $opt in
+
+  	h)
+		usage
+		exit 1
+	;;	 
+		
+    \?)
+		echo "Invalid option: -$OPTARG" >&2
+		exit 1
+	;;
+  esac
+done
+
+
+############################################################################# 
 # Check usage
 #############################################################################
 
